spring.application.name=competition

spring.config.import=optional:classpath:application-local.properties

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml